### ISSUE TITLE
How I can try to use v3?

### ISSUE THREAD

**Issue by melkayam92** [googleapis/python-bigtable#812]
Currently, I am using the bigtable_v2 async client, which generally works well. However, I have observed a spike in latency every hour. I suspect this may be due to the GRPC channel closing after 1 hour. Upon reviewing the v3 code, I discovered the presence of a grpc connection pool, which seems promising for resolving my issue.

I attempted to install the branch using pip, but it was unsuccessful. Do you have any suggestions on how I can test it?

**Comment by daniel-sanche** [comment]
We're planning on cutting the first alpha release at the end of the week, so I'd recommend waiting for that. I believe it will be released as a developer pre-release on pypi, but you should also be able to install builds directly from the repo by cloning it and installing with `pip install -e .`  If you're having issues with that let, me know (currently you also need to clone and install the `python-api-core` sub-module, but that won't be required after the alpha this week)

If you decide to try out the alpha and have any feedback, please reach out!

**Comment by daniel-sanche** [comment]
As for the latency spike you're seeing, it could be due to the channels needing refresh, or it could also be due to oauth credentials expiring and [needing refresh](https://github.com/googleapis/google-auth-library-python/blob/36bba1382a273f06a49cb0ef2cd08fa7815d5246/google/oauth2/credentials.py#L295), which I believe also happens ~hourly. The channel pool in the alpha should address the first one, but auth token refresh is [coming later](https://github.com/googleapis/python-bigtable/issues/813).

**Comment by melkayam92** [comment]
Thanks @daniel-sanche , I will wait for the alpha. 

For now, I have implemented a workaround where I warm up a different client every 50 minutes. It seems to have resolved the issue with the spikes.

**Comment by triplequark** [comment]
Closing as v3 client will resolve - please re-open if needed for any reason.
